### ISSUE TITLE
Project idea - URL shortener generator 

### ISSUE THREAD

**Issue by marekdano** [codu-code/project-ideas#1]
## URL shortener generator
Tier: Intermediate

The application should have input where an URL address can be added and a button to generate a short URL.

The application can be hosted on Heroku on any free host providers.

This also could be a good practice to prepare for tech interviews as most companies ask about it in their interview process.

**Comment by NiallJoeMaher** [comment]
@marekdano Nice that's a great idea, would you open a PR and add it to the list?
